### ISSUE TITLE
something dies handling cmd parameters... 

### ISSUE THREAD

**Issue by techdragon** [mitchellh/veewee-to-packer#13]
I dont do much (read any) ruby so I haven't a clue how to fix this, but yeah. it doesnt work. Tried every combination of cmd line options i could think of but all it ever does is print this error. googling lead no where, and to be honest, given the lack of documentation regarding any required version of ruby, I figure theres some kind of bug here, even if its just documentation related since i followed the instructions to install it correctly.

```
veewee-to-packer --builder vmware, -o /Users/redacted/Dev/project/vms  definitions/gentoo-mk1/definition.rb    1 
/Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1372:in `copy_stream': Is a directory - read (Errno::EISDIR)
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1372:in `block (2 levels) in copy_file'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1371:in `open'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1371:in `block in copy_file'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1370:in `open'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1370:in `copy_file'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:477:in `copy_file'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:396:in `block in cp'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:395:in `cp'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/veewee-to-packer-0.2.1/lib/veewee-to-packer/builders/vmware.rb:148:in `block in convert'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/veewee-to-packer-0.2.1/lib/veewee-to-packer/builders/vmware.rb:145:in `each'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/veewee-to-packer-0.2.1/lib/veewee-to-packer/builders/vmware.rb:145:in `convert'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/veewee-to-packer-0.2.1/lib/veewee-to-packer.rb:116:in `block in convert'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/veewee-to-packer-0.2.1/lib/veewee-to-packer.rb:115:in `map'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/veewee-to-packer-0.2.1/lib/veewee-to-packer.rb:115:in `convert'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/veewee-to-packer-0.2.1/bin/veewee-to-packer:38:in `<top (required)>'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/bin/veewee-to-packer:23:in `load'
    from /Users/redacted/.rbenv/versions/1.9.3-p327/bin/veewee-to-packer:23:in `<main>'
```

**Comment by mitchellh** [comment]
Thanks confirmed the bug, looking into it.

**Comment by mitchellh** [comment]
Fixed and pushed a release. Thanks.
