### ISSUE TITLE
No implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by jen20** [mitchellh/veewee-to-packer#24]
Trying to convert some of the Veewee Windows templates to packer, I get the following error. I'm running master of veewee-to-packer rather than the version on gems, but the same occurs in both. Is this likely to be a problem with the template itself (others work successfully)?

```
$ bundle exec veewee-to-packer templates/windows-2012R2-serverdatacenter-amd64/definition.rb
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/veewee-to-packer-e34d64b8f5de/lib/veewee-to-packer.rb:80:in `gsub': no implicit conversion of nil into String (TypeError)
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/veewee-to-packer-e34d64b8f5de/lib/veewee-to-packer.rb:80:in `block in convert'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/veewee-to-packer-e34d64b8f5de/lib/veewee-to-packer.rb:78:in `each'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/veewee-to-packer-e34d64b8f5de/lib/veewee-to-packer.rb:78:in `convert'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/veewee-to-packer-e34d64b8f5de/bin/veewee-to-packer:43:in `<top (required)>'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bin/veewee-to-packer:23:in `load'
    from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bin/veewee-to-packer:23:in `<main>'
```

**Comment by ericberens** [comment]
Fails because it is looking for an undefined `:ssh_password` in the Windows templates. A workaround would just be to add `:ssh_password => "",` to your definition.rb file for the specific template.

veewee-to-packer.rb:80 should null check `(definition[:ssh_password] || "")` or `definition[:ssh_password].to_s`. I believe that would resolve the issue.
