### ISSUE TITLE
 undefined method `declare_yaml' for Veewee::Definition:Class

### ISSUE THREAD

**Issue by Falkor** [mitchellh/veewee-to-packer#25]
If I try to use `veewee-to-packer` (version 0.3.0) to  convert any of the officials [veewee templates for Debian 8.*](https://github.com/jedi4ever/veewee/tree/master/templates/Debian-8), it fails with error `undefined method`declare_yaml' for Veewee::Definition:Class`:

```
$> veewee-to-packer --version 
veewee-to-packer 0.3.0

$> veewee-to-packer -o packer/debian-8 .submodules/veewee/templates/Debian-8/definition.rb
<path>/.submodules/veewee/templates/Debian-8/definition.rb:1:in `<top (required)>': undefined method `declare_yaml' for Veewee::Definition:Class (NoMethodError)
    from <path>veewee-to-packer-0.3.0/lib/veewee-to-packer.rb:36:in `load'
    from <path>veewee-to-packer-0.3.0/lib/veewee-to-packer.rb:36:in `convert'
    from <path>/veewee-to-packer-0.3.0/bin/veewee-to-packer:43:in `<top (required)>'
    from <path>/veewee-to-packer:23:in `load'
    [...]
```

it seems `veewee-to-packer` fails to handle the following (valid) syntax for [`definition.rb`](https://github.com/jedi4ever/veewee/blob/master/templates/Debian-8/definition.rb):

``` ruby
Veewee::Definition.declare_yaml('definition.yml', '8.6.yml')
```

**Comment by UniIsland** [comment]
+1 for this 2-year-old issue.
